version: '3.3'
services:
  web-db: 
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=scholee
      - MYSQL_USER=scholee
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  web-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.0-apache
    volumes:
      - ".:/var/www/html"
    ports:
      - 3000:80
    depends_on:
      - web-db
